steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/udemy-mlops-430513/advertising_roi_model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/udemy-mlops-430513/advertising_roi']

- name: 'gcr.io/udemy-mlops-430513/advertising_roi'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/saquibherman/advertisement-roi-model-training-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'advertisement-roi-model-training-repo/advertising_model_training.py', 'gs://us-central1-mlops-airflow-9699781c-bucket/dags']

images:
- 'gcr.io/udemy-mlops-430513/advertising_roi'

options:
  logging: CLOUD_LOGGING_ONLY